project:
  type: website

website:
  title: "Reiter on the storm"
  image: img1.jpg
  navbar:
    tools:
    right:
      - text: "{{< iconify fa6-brands bluesky >}}"
        href: https://twitter.com/leonhard_reiter
      - icon: twitter
        href: https://twitter.com/leonhard_reiter
      - icon: github
        href: https://github.com/leonhardreitr
      - icon: envelope
        href: "mailto:leonhard.reiter@univie.ac.at"
      - text: "{{< iconify academicons osf-square >}}"
        href: https://osf.io/profile/
      - icon: linkedin
        href: https://www.linkedin.com/in/leonhard-reiter-a93470229/
      - text: "{{< iconify fa6-brands orcid >}}"
        href: https://orcid.org/0000-0002-2400-7907
      - text: "{{< iconify fa6-brands google-scholar >}}"
        href: https://scholar.google.com/citations?user=nibOPBsAAAAJ&hl=en
  
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: cv.qmd
        text: My CV
      - href: research/pub.qmd
        text: Publications
      - posts.qmd

format:
  html:
    theme:
      light: [cosmo, cosmo_costum.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: Nunito
   # css: styles.css


