project:
  type: website

website:
  title: "Reiter on the storm"
  image: img2.jpeg
  navbar:
    tools:
    right:
      - icon: twitter
        href: https://twitter.com/leonhard_reiter
      - icon: github
        href: https://github.com/leonhardreitr
      - icon: envelope
        href: "mailto:leonhard.reiter@univie.ac.at"
      - icon: box-fill
        text: OSF
        href: https://osf.io/profile/
      - icon: linkedin
        href: https://www.linkedin.com/in/leonhard-reiter-a93470229/
  
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - cv.qmd

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    mainfont: Nunito
   # css: styles.css


