project:
  type: website

website:
  title: "Reiter on the storm"
  navbar:
    tools:
      - icon: twitter
        href: https://twitter.com/leonhard_reiter
      - icon: github
        href: https://github.com/leonhardreitr
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - cv.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


