---
title: "About me"
editor: 
  markdown: 
    wrap: 72
---

My name is Leonhard Reiter, but most people just call me Lenni[^1]. This
fall I will start as a Marketing Phd Student in Christoph Fuchs team at
the university of Vienna.

[^1]: With an "i" not a "y"

Before that I studied Psychology at the university of Vienna (M.Sc) and
was a student assistant in Robert Böhm's Team. There I helped with
conducting research, such as creating surveys and analyzing data.

I did an internship at Susann Fiedler's group at the WU Vienna where I
prepared a Bachelor course on Publication Bias detection methods such as
p/z-curves regarding management research.

I am interested in how people engage, rate and interact with new
technologies, ranging from algorithms to vaccines. Furthermore I am also
interested in more meta-sciency topics such as p-mining, publication
bias and how to help to improve science. My research was featured in
popular media such as the [Forbes
magazine](https://www.forbes.com/sites/charlestowersclark/2024/03/15/3-ways-to-use-ai-for-strategic-decision-making/)

My work is strongly quantitative and I love doing and reading about
statistics. Check my Github to see what I am currently working through.

Sometime I also dabble into Bayesian barbarism, participating in the
2024 edition of Richard McElreath's "Statistical Rethinking"-Course.
More broadly I am interested in meta-analyses, mixed-effects models,
Machine Learning and text as data. I strongly advocate open-science and
especially reproducible workflows. Check out my OSF to see more.

Beside science I am an avid martial artis (Purple Belt in BJJ), like to
cook, play Bass and take long walks in the
[Augarten](https://de.wikivoyage.org/wiki/Wien/Leopoldstadt/Augarten#/media/Datei:Augarten_Flakturm.jpg).

If you would like to talk about statistics, science in general or to
collaborate on a project, feel free to reach out to me via mail.
