
# website settings
website:
  title: "Leonhard Reiter"                                
 # description: ""   # A brief slogan (optional)
  image: img/my_image.jpg
  
  #favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
   # logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "CV"
        href: cv/cv.qmd
      #- text: "Books"
    
    # your social media handles
    right:
      - icon: github
        href: https://github.com/leonhardreitr
      - icon: twitter
        href: https://twitter.com/leonhard_reiter
      - icon: linkedin
        href: https://linkedin.com/in/leonhard-reiter-a93470229
      - icon: osf
        text: OSF
        href: https://osf.io/5zu6h/
      - icon: envelope
        aria-label: email
        href: "mailto:leonhard.reiter@univie.ac.at" 

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  
project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - cosmo
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true